version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data # Mapeia o volume para persistir os dados do CIFAR-10
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    # Se você tiver GPU e suporte a CUDA no seu sistema:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

  frontend:
    build: ./frontend # Você precisará de um Dockerfile para o frontend também, ou pode servir estaticamente
    ports:
      - "80:80"
    depends_on:
      - backend