# frontend/Dockerfile
FROM nginx:alpine

# Copia todos os arquivos da pasta 'frontend' (onde este Dockerfile está)
# para o diretório padrão de servir arquivos do Nginx dentro do container.
COPY . /usr/share/nginx/html